### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Penton** [yehuio/Coot#3]
**环境：**
Centos 7.5 
go version go1.11.5 linux/amd64
（Mac下正常运行）
——————————————————————————————————————————

**报错：**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8fddd0]

goroutine 1 [running]:
sync.(*RWMutex).RLock(...)
	/usr/local/Cellar/go/1.12.7/libexec/src/sync/rwmutex.go:48
database/sql.(*Stmt).ExecContext(0x0, 0xb357e0, 0xc0000200c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:2307 +0x50
database/sql.(*Stmt).Exec(...)
	/usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:2336
Coot/core/dbUtil.Update(0xa698ed, 0x2b, 0x0, 0x0, 0x0, 0x0)
	/Users/sanjin/work/go/coot/src/Coot/core/dbUtil/dbUtil.go:83 +0xcb
Coot/view/task.UpdateTaskAll(...)
	/Users/sanjin/work/go/coot/src/Coot/view/task/view.go:119
Coot/utils/setting.RunWeb(0xa58959, 0xe)
	/Users/sanjin/work/go/coot/src/Coot/utils/setting/setting.go:30 +0x156
main.main()
	/Users/sanjin/work/go/coot/src/Coot/main.go:24 +0x21a

**Comment by lauixData** [comment]
@Penton Mac 版本 不能用在 Linux 上，只能使用 Linux 版本。

**Comment by Penton** [comment]
@lauixData Linux上用的是Linux版本啊

**Comment by lauixData** [comment]
@Penton 经过测试确实有这个问题，正在查找定位

**Comment by alin299** [comment]
+1。:frowning:

**Comment by lauixData** [comment]
有个组件采用 cgo ，linux 跨平台编译有问题，所以请下载源码在自己平台上编译使用，后续会打包相应的版本
