### ISSUE TITLE
linux运行有问题

### ISSUE THREAD

**Issue by lwydyby** [yehuio/Coot#4]
[GIN-debug] GET    /static/*filepath         --> Coot/vendor/github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /static/*filepath         --> Coot/vendor/github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] GET    /                         --> Coot/view/dashboard.Html (3 handlers)
[GIN-debug] GET    /dashboard                --> Coot/view/dashboard.Html (3 handlers)
[GIN-debug] GET    /task                     --> Coot/view/task.Html (3 handlers)
[GIN-debug] GET    /task/add                 --> Coot/view/task.HtmlAdd (3 handlers)
[GIN-debug] GET    /get/task/list            --> Coot/view/task.GetTaskList (3 handlers)
[GIN-debug] POST   /post/task/add            --> Coot/view/task.PostTaskAdd (3 handlers)
[GIN-debug] POST   /post/task/del            --> Coot/view/task.PostTaskDel (3 handlers)
[GIN-debug] POST   /task/start               --> Coot/view/task.TaskStart (3 handlers)
[GIN-debug] POST   /task/stop                --> Coot/view/task.TaskStop (3 handlers)
[GIN-debug] GET    /plugs                    --> Coot/view/plug.Html (3 handlers)
[GIN-debug] GET    /setting                  --> Coot/view/setting.Html (3 handlers)
[GIN-debug] GET    /get/setting/info         --> Coot/view/setting.GetSettingInfo (3 handlers)
[GIN-debug] POST   /post/setting/update      --> Coot/view/setting.UpdateEmailInfo (3 handlers)
[GIN-debug] POST   /post/setting/login       --> Coot/view/setting.UpdateLoginInfo (3 handlers)
[GIN-debug] POST   /post/setting/checkSetting --> Coot/view/setting.UpdateStatusSetting (3 handlers)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8fddd0]

goroutine 1 [running]:
sync.(*RWMutex).RLock(...)
	/usr/local/Cellar/go/1.12.7/libexec/src/sync/rwmutex.go:48
database/sql.(*Stmt).ExecContext(0x0, 0xb357e0, 0xc000020090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:2307 +0x50
database/sql.(*Stmt).Exec(...)
	/usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:2336
Coot/core/dbUtil.Update(0xa698ed, 0x2b, 0x0, 0x0, 0x0, 0x0)
	/Users/sanjin/work/go/coot/src/Coot/core/dbUtil/dbUtil.go:83 +0xcb
Coot/view/task.UpdateTaskAll(...)
	/Users/sanjin/work/go/coot/src/Coot/view/task/view.go:119
Coot/utils/setting.RunWeb(0xa58959, 0xe)
	/Users/sanjin/work/go/coot/src/Coot/utils/setting/setting.go:30 +0x156
main.main()
	/Users/sanjin/work/go/coot/src/Coot/main.go:24 +0x21a

**Comment by lwydyby** [comment]
运行的是编译好的linux版

**Comment by lauixData** [comment]
编译的版本有问题，请自行编译。or 进群等新版发布通知
